dental_staff/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
import django_heroku
from dental_staff import views
from api import views as api_views
from manager import views as manager_views


api_urlpatterns = [
    path('socials/', api_views.socials_get, name="get_socials"),
    path('announcements/', api_views.announcements_get, name="get_announcements"),
    path('subjects/<int:uid>/', api_views.subjects_get, name="get_subject"),
    path('subjects/', api_views.subjects_get, name="get_subjects"),
    path('subjects/<int:uid>/textbooks/',
         api_views.textbooks_get, name="get_textbooks"),
    path('subjects/<int:uid>/lecture/',
         api_views.lectures_get, name="get_lectures"),
    path('content/', api_views.content_get, name="get_content"),
    path('content/<int:uid>/label',
         api_views.content_update, name="update_content"),
    path('content/tags', api_views.content_tag, name="create_tag"),
    path('auth/', include('rest_framework.urls')),
    path('links/', api_views.useful_link_get, name="get_links"),
    path('subjects/delete/', api_views.delete_module, name="delete_module"),
    path('content/delete/', api_views.delete_content, name="delete_content"),
    path('subsection/delete/', api_views.delete_subsection, name="delete_subsection"),
    path('section/delete/', api_views.delete_lecture_section, name="delete_lecture_section"),
]

urlpatterns = [
    path('api/', include(api_urlpatterns)),
    path('manager/', include('manager.urls')),
    path('socials_announcements/', include('socials_announcements.urls')),
    path('admin/', admin.site.urls),
    path('', views.manage_modules),
    path('manage-modules/', views.manage_modules, name="manage-modules"),
    path('add-module/', views.add_module, name="add-module"),
    path('view-module/', views.view_module, name="view-module"),
    path('add-lecture-section/', views.add_lecture_section, name="add_lecture_section"),
    path('add-subsection/', views.add_subsection, name="add-subsection"),
    path('add-content/', views.add_content, name="add-content"),
    path('edit-content/', views.edit_content, name="edit-content"),
    path('edit-subsection/', views.edit_subsection, name="edit-subsection"),
    path('manage-socials-access/', views.manage_socials_access, name="manage-socials-access"),
    path('view-posts/', views.view_posts, name="view-posts"),
    path('manage-socials/',views.manage_socials_landing, name='manage-socials'),
    path('make-an-announcement/',views.announcement, name="make-an-announcement"),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('uploader/' , views.uploader, name='uploader'),
]

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'

'''
Registering the urls for managers
'''

urlpatterns = [
    path('', views.home, name="home"),
    path('register/', views.register, name="register"),
    path('revoke/', views.revoke, name="revoke"),
]

socials_announcements/urls.py
from django.urls import path
from . import views

'''
Urls.py 

Registers social_announcements urls
'''

app_name = 'socials_announcements'

urlpatterns = [
    path('socials/', views.socials, name="socials"),
    path('links/', views.links, name="links"),
    path('revoke/', views.revoke, name="revoke"),
]

dental_staff/forms.py
import sys
from django import forms
from uploader.models import Announcements, Subject, LectureSection, Subsection, Content

'''
Forms.py 

Creates all the necessary forms to allow users to add and remove new content for each of the models
'''

class AnnouncementForm(forms.ModelForm):
    class Meta:
        model = Announcements
        fields = ('title', 'content')

class ModuleForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ('title', 'year', 'image', 'moodle_link')

class LectureSectionForm(forms.ModelForm):
    class Meta:
        model = LectureSection
        fields = ('title','description')

class SubsectionForm(forms.ModelForm):
    class Meta:
        model = Subsection
        fields = ("title",)

class ContentForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = ('file', 'due_date')

manager/forms.py
from django import forms
from django.forms import ValidationError
from uploader.models import Subject

'''
Forms.py 

Creates the form to allow users to upload a file with user details to 
allow them access to the app

'''

class UserCsvForm(forms.Form):
	email = forms.EmailField(required=False)
	file = forms.FileField(required=False)
	is_lecturer = forms.BooleanField(required=False)
	is_secretary = forms.BooleanField(required=False)
	is_admin = forms.BooleanField(required=False)
	# TODO
	# Add redirect link to subject creation page
	subjects = forms.ModelMultipleChoiceField(
		queryset=Subject.objects.all(), 
		required=False,
		help_text="If you can't see the subject you are looking for, you can "
		"create one ", )

	def clean(self):
		"""Custom form validation method
		
		The following checks are performed

		1. File extension is valid
		2. At least one field is not empty
		3. Email is valid
		4. Permissions are valid and the user is allowed to set them
		
		Returns:
			[dictionary] -- dict containing cleaned (normalized) data 
		
		Raises:
			ValidationError -- see checks above
		"""
		email = self.cleaned_data.get('email')
		file = self.cleaned_data.get('file')
		is_lecturer = self.cleaned_data.get('is_lecturer')
		is_secretary = self.cleaned_data.get('is_secretary')
		is_admin = self.cleaned_data.get('is_admin')
		subjects = self.cleaned_data.get('subjects')

		valid_extensions = ['xlsx', 'xlsm', 'csv', 'xls']

		if file:
			extension = file.name.split('.')[-1]
			if extension  not in valid_extensions:
				raise forms.ValidationError("Invalid file format."
					f"The only valid formats are {valid_extensions}")
		if not email and not file:
			raise forms.ValidationError("Please choose at least one")
		if email != "" and ("gla.ac.uk" not in email 
								and "glasgow.ac.uk" not in email):
			raise forms.ValidationError("A valid GU email address is required")
		
		
		if (is_lecturer and is_secretary or 
			(is_secretary and subjects.exists())):
			raise forms.ValidationError("Secretaries should not "
				"have access to course materials. "
				"You can make a lecturer an admin "
				"but note that this user will have "
				"full access rights")
		if is_secretary and is_admin:
			raise forms.ValidationError("An admin has all the permissions of "
				"a secretary. Please choose admin only")
		if is_lecturer and not subjects.exists():
			raise forms.ValidationError("A lecturer requires a subject")
		return self.cleaned_data

dental_staff/views.py
import os
import requests
import sys
from .forms import AnnouncementForm, ModuleForm, LectureSectionForm, SubsectionForm, ContentForm
from uploader.models import *
from datetime import datetime
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages


'''
Views.py 

All these views deal with the actions and logic of each page.
'''

# Viewing posts (not finished yet)
def view_posts(request):
    return render(request, 'view-posts.html')
	
# managing socials access (not finished yet)
def manage_socials_access(request):
    return render(request, 'manage-socials-access.html')

# Allows users to login to the site, will only allow proper users to access the site
def user_login(request):
	ERROR_MESSAGE = f"You are not allowed to login. If you think this\
				is a mistake, please contact"

	if request.user.is_authenticated :
		messages.error(request, "You are already logged in")
		if request.user.is_superuser:
			return redirect(reverse('manage-modules'))
		if request.user.is_staff:
			return redirect(reverse('manager:home'))
		return redirect(reverse('uploader'))

	if request.method == 'POST':
		email = request.POST.get('email')
		password = request.POST.get('password')
		if "student" in email:
			messages.error(request,"Students are not allowed access")
			return redirect(reverse('login'))
		auth = firebase_authenticate(email=email, password=password)
		if auth.status_code != 200:
			messages.error(request,'Invalid login details.')
			return redirect(reverse('login'))
		try:
			user = User.objects.get(email=email)
		except Exception as e:
			return redirect(reverse('login'))
		if user.is_active:
			login(request, user)
			if user.is_superuser:
				return redirect(reverse('manage-modules'))
			if user.is_staff:
				return redirect(reverse('manager:home'))
			return redirect(reverse('uploader'))
		else:
			messages.error(request,ERROR_MESSAGE)
			return redirect(reverse('login'))
	else:
		return render(request, 'login.html',)

# Logs the user out of the site
def user_logout(request):
	logout(request)
	return redirect(reverse('login'))

# Manage socials main page
def manage_socials_landing(request):
    return render(request, 'manage_socials_landing.html')

# Allows users to make an announcement
def announcement(request):
    if request.method == 'POST':
        form = AnnouncementForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Announcement Submission Successful")
            form = AnnouncementForm()
    else:
        form = AnnouncementForm()
    return render(request, 'make-an-announcement.html', {'form': form})

# Authenticates users when they login
def firebase_authenticate(email, password):
	endpoint = "https://identitytoolkit.googleapis.com/v1/accounts"
	API_KEY = os.environ['FIREBASE_API_KEY']
	r = requests.post(f"{endpoint}:signInWithPassword?key={API_KEY}",
		params={'email':email, 'password':password})
	return r

# manage modules main page; shows all modules
def manage_modules(request):
    module_list = Subject.objects.all()
    context_dict = {}
    context_dict['modules'] = module_list
    return render(request, 'manage-modules.html', context=context_dict)

# Shows a specific module with all the sections, subsections, content, etc... assigned to that module
def view_module(request):
    module_list = Subject.objects.all()
    section_list = LectureSection.objects.all()
    subsection_list = Subsection.objects.all()
    content_list = Content.objects.all()
    context_dict = {}
    context_dict['modules'] = module_list
    context_dict['sections'] = section_list
    context_dict['content'] = content_list
    context_dict['subsections'] = subsection_list
    return render(request, 'view-module.html', context=context_dict)

# Allows users to add a new module the site
def add_module(request):
    if request.method == 'POST':
        form = ModuleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Module Submission Successful")
            form = ModuleForm()
    else:
        form = ModuleForm()
    return render(request, 'add-module.html', {'form': form})

# Allows users to add a new section to a module
def add_lecture_section(request):
    if request.method == 'POST':
        moduleID = request.GET.get('id')
        module = Subject.objects.get(id=moduleID)
        form = LectureSectionForm(request.POST)
        if form.is_valid():
            new_lecture_section = form.save(commit=False)
            new_lecture_section.subject = module
            new_lecture_section.created_at = datetime.now()
            new_lecture_section.save()
            messages.success(request, "Lecture Section Submission Successful")
            form = LectureSectionForm()
    else:
        form = LectureSectionForm()
    return render(request, 'add-lecturesection.html', {'form': form})

# Allows users to add a new subsection to a module
def add_subsection(request):
    if request.method == 'POST':
        sectionID = request.GET.get('id')
        section = LectureSection.objects.get(id=sectionID)
        form = SubsectionForm(request.POST)
        if form.is_valid():
            new_section = form.save(commit=False)
            new_section.lecture_section = section
            new_section.created_at = datetime.now()
            new_section.save()
            messages.success(request, "Subsection Submission Successful")
            form = SubsectionForm()
    else:
        form = SubsectionForm()
    return render(request, 'add-subsection.html', {'form': form})

# Allows users to add new content to a section/subsection
def add_content(request):
    if request.method == 'POST':
        subsectionID = request.GET.get('id')
        subsection = Subsection.objects.get(id=subsectionID)
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            new_subsection = form.save(commit=False)
            new_subsection.subsection = subsection
            new_subsection.created_at = datetime.now()
            new_subsection.save()
            messages.success(request, "Content Submission Successful")
            form = ContentForm()
    else:
        form = ContentForm()
    return render(request, 'add-content.html', {'form': form})

# Allows users to change the uploaded content 
def edit_content(request):
    if request.method == 'POST':
        contentID = request.GET.get('id')
        content = Content.objects.get(id=contentID)
        form = ContentForm(request.POST, request.FILES, instance=content)
        if form.is_valid():
            new_content = form.save(commit=False)
            new_content.created_at = content.created_at
            new_content.subsection = content.subsection
            new_content.save()
            messages.success(request, "Content Update Successful")
            form = ContentForm()
    else:
        contentID = request.GET.get('id')
        content = Content.objects.get(id=contentID)
        form = ContentForm(instance=content)
    return render(request, 'edit-content.html', {'form': form})

# Allows users to edit the content inside a subsection
def edit_subsection(request):
    if request.method == 'POST':
        subsectonID = request.GET.get('id')
        subsection = Subsection.objects.get(id=subsectonID)
        form = SubsectionForm(request.POST, request.FILES, instance=subsection)
        if form.is_valid():
            new_subsection = form.save(commit=False)
            new_subsection.created_at = subsection.created_at
            new_subsection.lecture_section = subsection.lecture_section
            new_subsection.save()
            messages.success(request, "Subsection Update Successful")
            form = SubsectionForm()
    else:
        subsectonID = request.GET.get('id')
        subsection = Subsection.objects.get(id=subsectonID)
        form = SubsectionForm(instance=subsection)
    return render(request, 'edit-subsection.html', {'form': form})

# Uploader page
def uploader(request):
	html = "<h1>uploader</h1>"
	return HttpResponse(html)

dental_staff/templates/403_csrf.html
<!--SOURCE https://github.com/h5bp/html5-boilerplate/blob/master/src/404.html-->
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>403 - Forbidden</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>

  footer{
      position: fixed;
      bottom: 10em;
      width: 100%;
    }
    
    * {
      line-height: 1.2;
      margin: 0;
    }

    html {
      color: #888;
      display: table;
      font-family: sans-serif;
      height: 100%;
      text-align: center;
      width: 100%;
    }

    body {
      display: table-cell;
      vertical-align: middle;
      margin: 2em auto;
    }

    h1 {
      color: #555;
      font-size: 2em;
      font-weight: 400;
    }

    p {
      margin: 0 auto;
      width: 280px;
    }

    @media only screen and (max-width: 280px) {

      body,
      p {
        width: 95%;
      }

      h1 {
        font-size: 1.5em;
        margin: 0 0 0.3em;
      }

    }
  </style>
</head>

<body>
  <h1>Access Denied</h1>
  <p>Please contact your administrator if you think this was a mistake</p>
</body>

<footer>
  Admin &#9993; 
    <a href="mailto:david.cross@glasgow.ac.uk">david.cross@glasgow.ac.uk</a>
</footer>
</html>

dental_staff/templates/add-content.html
<!DOCTYPE html>
{%extends 'base.html' %}
{% load crispy_forms_tags %}
<html>
   {% load static %}
   <head>
      <title>Add Content</title>
      {% block title_block %} Add Content {% endblock %}
   </head>
   <body>
      {% block body_block %}
      <br>
      <div class="textbox">
         <h1 style="color: black;" class="text-center">Add Content</h1>
      </div>
          <div class="middlebox">
      {% block content %}
      <form style="text-align: center;" method="POST" enctype="multipart/form-data">
         {%csrf_token%}
         {{ form|crispy }}
         <button class="submitButton" type="submit" id="submit">Submit</button>
         {% if messages %}
         {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
         {% endfor %}
         {% endif %}
      </form>
      {% endblock %}
      </div>
      </form>
      </div>
          </div>
      {% endblock %}
   </body>
</html>

dental_staff/templates/add-lecturesection.html
<!DOCTYPE html>
{%extends 'base.html' %} {% load crispy_forms_tags %}

<html>
    {% load static %}

    <head>
        <title>Manage Lecture Sections</title>
    </head>
    <body>
        {% block body_block %}

        <br />
        <div class="textbox">
            <h1 style="color: black;" class="text-center">Add Lecture Section</h1>
        </div>
        <div class="middlebox">
            {% block content %}

            <form style="text-align: center;" method="POST">
                {%csrf_token%} {{ form|crispy }}

                <button class="submitButton" type="submit" id="submit">Submit</button>
            {% if messages %}
         {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
         {% endfor %}
         {% endif %}
            </form>
            {% endblock %}
        </div>
        {% endblock %}
    </body>
</html>

dental_staff/templates/add-module.html
<!DOCTYPE html>
{%extends 'base.html' %}
{% load crispy_forms_tags %}
<html>
   {% load static %}
   <head>
      <title>Manage Lecture Sections</title>
      {% block title_block %} Manage Lecture Sections {% endblock %}
   </head>
   <body>
      {% block body_block %}
      <br>
      <div class="textbox">
         <h1 style="color: black;" class="text-center">Add Module</h1>
      </div>
          <div class="middlebox">
      {% block content %}
      <form style="text-align: center;" method="POST" enctype="multipart/form-data">
         {%csrf_token%}
         {{ form|crispy }}
         <button class="submitButton" type="submit" id="submit">Submit</button>
          {% if messages %}
              {% for message in messages %}
                  {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
              {% endfor %}
         {% endif %}
      </form>
      {% endblock %}
      </div>
      </form>
      </div>
          </div>
      {% endblock %}
   </body>
</html>

dental_staff/templates/add-subsection.html
<!DOCTYPE html>
{%extends 'base.html' %}
{% load crispy_forms_tags %}
<html>
   {% load static %}
   <head>
      <title>Add Subsection</title>
      {% block title_block %} Add Subsection {% endblock %}
   </head>
   <body>
      {% block body_block %}
      <br>
      <div class="textbox">
         <h1 style="color: black;" class="text-center">Add Subsection</h1>
      </div>
          <div class="middlebox">
      {% block content %}
      <form style="text-align: center;" method="POST" enctype="multipart/form-data">
         {%csrf_token%}
         {{ form|crispy }}
         <button class="submitButton" type="submit" id="submit">Submit</button>
         {% if messages %}
         {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
         {% endfor %}
         {% endif %}
      </form>
      {% endblock %}
      </div>
      </form>
      </div>
          </div>
      {% endblock %}
   </body>
</html>

dental_staff/templates/edit-content.html
<!DOCTYPE html>
{%extends 'base.html' %}
{% load crispy_forms_tags %}
<html>
   {% load static %}
   <head>
      <title>Edit Content</title>
      {% block title_block %} Edit Content {% endblock %}
   </head>
   <body>
      {% block body_block %}
      <br>
      <div class="textbox">
         <h1 style="color: black;" class="text-center">Edit Content</h1>
      </div>
          <div class="middlebox">
      {% block content %}
      <form style="text-align: center;" method="POST" enctype="multipart/form-data">
         {%csrf_token%}
         {{ form|crispy }}
         <button class="submitButton" type="submit" id="submit">Submit</button>

         {% if messages %}
         {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
         {% endfor %}
         {% endif %}
      </form>
          <div class="text-center pt-3">
              <button class="submitButton" onclick="deleteContent({{ request.GET.id }})">Delete</button>
          </div>

      {% endblock %}
      </div>
      </form>
      </div>
          </div>
      {% endblock %}
   </body>
</html>

dental_staff/templates/edit-subsection.html
<!DOCTYPE html>
{%extends 'base.html' %}
{% load crispy_forms_tags %}
<html>
   {% load static %}
   <head>
      <title>Edit Subsection</title>
      {% block title_block %} Edit Subsection {% endblock %}
   </head>
   <body>
      {% block body_block %}
      <br>
      <div class="textbox">
         <h1 style="color: black;" class="text-center">Edit Subsection</h1>
      </div>
          <div class="middlebox">
      {% block content %}
      <form style="text-align: center;" method="POST" enctype="multipart/form-data">
         {%csrf_token%}
         {{ form|crispy }}
         <button class="submitButton" type="submit" id="submit">Submit</button>

         {% if messages %}
         {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
         {% endfor %}
         {% endif %}
      </form>
          <div class="text-center pt-3">
              <button class="submitButton" onclick="deleteSubsection({{ request.GET.id }})">Delete</button>
          </div>

      {% endblock %}
      </div>
      </form>
      </div>
          </div>
      {% endblock %}
   </body>
</html>

dental_staff/templates/forms_base.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block body_block %}
    {% block form_block %}
        <div class="form_container mt-3">

            <h1 class="text-center">{% block form_header_block %}
                {% endblock %}</h1>

                <form style="text-align: center;" method="POST">
                    {%csrf_token%}
                    
                    {{ form|crispy }}
                    

                    <button class="submitButton" type="submit" id="submit">Submit</button>

                </form>
        </div>

    {% endblock %}
{% endblock %}

dental_staff/templates/make-an-announcement.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<html>
    <head>
        <title>Make an Announcement</title>
        {% block title_block %} Make an Announcement {% endblock %}
    </head>

    <body>
        {% block body_block %}
            <div class="announcement mt-3">

                <h1 class="text-center">Make An Announcement</h1>

                    {% block content %}
                    <form style="text-align: center;" method="POST">
                        {%csrf_token%}
                        
                        {{ form|crispy }}
                        

                        <button class="submitButton" type="submit" id="submit">Submit</button>

                        {% if messages %}
                        {% for message in messages %}
                         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
                
                        {% endfor %}
                
                    {% endif %}
                        

                    </form>
                    {% endblock %}
            </div>

        {% endblock %}
    </body>

</html>

dental_staff/templates/manage-register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
    <head>
        <title>Manage User Access</title>
    </head>

    <body>
        {% block body_block %}
        <div class="row justify-content-start">
            <h1>Manage User Access</h1>
            <h5 class="col" style="padding-top: 15px;">(Welcome, {{user}}!)</h5>
        </div>
                    {% block content %}
                    {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                    {% endif %}

                    <form id="form" method="post" action="{% url 'manager:register' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if user_form.errors %}
                        {{user_form.errors}}
                        {%endif%}
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label-lg">Email</label>
                            <div class="col-sm-10">
                              {{user_form.email}}
                            </div>
                          </div>
                          <div class="form-group row">
                            <label class="col-sm-2 col-form-label-lg">File</label>
                            <div class="col-sm-10">
                                <div class="custom-file register">
                                    {{user_form.file}}
                                    <label class="custom-file-label" for="customFile">Choose file</label>
                                </div>
                            </div>
                          </div>
                          
                          <fieldset class="form-group">
                            <div class="row">
                              <legend class="col-form-label-lg col-sm-2 pt-0">Roles</legend>
                              <div >
                                <div class="form-check">
                                    {{ user_form.is_lecturer }} 
                                    <label class="col-form-label-lg" for="id_is_lecturer">is_lecturer</label>
                                </div>
                                <div class="form-check">
                                    {{ user_form.is_secretary }} 
                                    <label class="col-form-label-lg" for="id_is_secretary">is_secretary</label>
                                </div>
                                <div class="form-check">
                                    {{ user_form.is_admin }}
                                    <label class="col-form-label-lg" for="id_is_admin">is_admin</label>
                                </div>
                              </div>
                            </div>
                          </fieldset>

                        <div class="form-group row">
                            <div class="col">
                                {{ user_form.subjects }}
                            </div>
                        </div>
                        <p style="
                        font-size: larger;">
                            {{user_form.subjects.help_text}} <a href="{% url 'add-module'%}">here</a>
                        </p>
                        <div class="form-group row justify-content-end">
                            <div class="col-1">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                            <div class="col-1"><button type="button" class="btn btn-danger" id="resetRegisterForm" onclick="customReset();">Reset Form</button></div>
                        </div>

                        
                        </form>


                    {% endblock %}
        <script>
            $("#id_file").addClass("custom-file-input");
            $('#id_file').on('change',function(){
                var pathlength = $(this).val().split('\\').length;
                var filename = $(this).val().split('\\')[pathlength-1];
                $(this).next('.custom-file-label').html(filename);
            });
            $("#body_block").removeClass("col-sm-6").addClass("col");


            function customReset()
            {
                document.getElementById("id_email").value = "";
                $(".custom-file-label").html("");
                document.getElementById("id_is_admin").checked = false;
                document.getElementById("id_is_secretary").checked = false;
                document.getElementById("id_is_lecturer").checked = false;
                $('select option:selected').removeAttr("selected");
            };

        </script>
        {% endblock %}
    </body>
</html>

dental_staff/templates/manage-socials-access.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<html>
    <head>
        <title>Manage Socials Access</title>
        {% block title_block %} Manage Socials Access {% endblock %}
    </head>

    <body>
        {% block body_block %}
       <br>
        <div class="textbox text-center"> 
        
            <h1 style="color: black;">Manage Socials Access</h1>
        

            <div class="text-center" style="color: black;">
                {% block content %}
                <form style="text-align: center;" method="POST">
                    {%csrf_token%}
                    
                    {{ form|crispy }}
                    

                    <button class="submitButton" type="submit" id="submit">Submit</button>
                    <a href="{% url 'socials_announcements:revoke' %}">Revoke Access</a>

                    {% if messages %}
                    {% for message in messages %}
                     {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
            
                    {% endfor %}
            
                {% endif %}


                </form>
                {% endblock %}
            </div>

        </div>
        {% endblock %}
    </body>
</html>

dental_staff/templates/view-posts.html
<!DOCTYPE html>
<html>
    {%extends 'base.html' %}
    {% load static %}
    <head>
        <title>View Posts</title>
        {% block title_block %} View Posts {% endblock %}
    </head>

    <body>
        {% block body_block %}
       <br>
        <div class="textbox"> 
        
            <h1 style="text-align:center; color: black;">Viewing Posts</h1>

            <div class="posts-1">

                <p style="color: black;">POSTS HERE</p>

            </div>

            <div class="posts-2">

                <p style="color: black;">POSTS HERE</p>

            </div>

            <div class="posts-3">

                <p style="color: black;">POSTS HERE</p>

            </div>

        </div>
        {% endblock %}
    </body>
</html>